services:
  - type: web
    name: moringa-techhub-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --worker-connections 1000
    envVars:
      - key: DATABASE_URL
        value: postgresql://moringa_techhubapi2_user:YPDX6uBfSR7S0B1BEyp0ruD5A13frPr7@dpg-d9oou4vlk1mc739mset0-a.oregon-postgres.render.com/moringa_techhubapi2
      - key: SEED_ON_START
        value: "true"
      - key: PERSISTENT_STORAGE
        value: "/opt/render/project/src/uploads"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: ENVIRONMENT
        value: "production"
    healthCheckPath: /health
    healthCheckTimeout: 30
    autoDeploy: true
    plan: starter