services:
  - type: web
    name: moringa-techhub-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --worker-connections 1000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moringa-techhub-db
          property: connectionString
      - key: SEED_ON_START
        value: "true"
      - key: PERSISTENT_STORAGE
        value: "/opt/render/project/src/uploads"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: ENVIRONMENT
        value: "production"
      - key: USE_POSTGRES
        value: "true"
    healthCheckPath: /health
    healthCheckTimeout: 30
    autoDeploy: true
    plan: starter
  - type: pserv
    name: moringa-techhub-db
    databaseName: moringa_techhub
    user: moringa_user